# Generated by Django 5.2.13 on 2026-04-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('seuil', models.IntegerField(default=10)),
                ('unite', models.CharField(max_length=50)),
                ('prix', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Matériau',
                'verbose_name_plural': 'Matériaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], max_length=10)),
                ('quantite', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('logement', models.CharField(blank=True, max_length=20)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='logi.materiau')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
