# Generated by Django 5.2.13 on 2026-04-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_logement', models.CharField(max_length=20, unique=True)),
                ('type_logement', models.CharField(choices=[('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('Villa', 'Villa'), ('Studio', 'Studio')], max_length=20)),
                ('localisation', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Occupé', 'Occupé'), ('Maintenance', 'Maintenance')], default='Disponible', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=1)),
                ('superficie', models.FloatField(default=0)),
                ('nb_occupants_max', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['id_logement'],
            },
        ),
    ]
